### ISSUE TITLE
Python Script Giving Different Results from Demo Site

### ISSUE THREAD

**Issue by seanlaw** [stanford-futuredata/ASAP#5] opened 2017-11-12 18:29 UTC
I created some fake data like this:

    n = 201
    x = np.linspace(0, 1, n)
    y = np.sin(4*np.pi*x*x)
    chirp = 0.5*np.sin((2.0*np.pi*x)/0.05)
    chirp_inx = np.argwhere((x > 0.4) & (x < 0.45))
    y[chirp_inx] = chirp[chirp_inx]
    noise = np.random.normal(0, 0.1, n)
    y_noise = y + noise

So, my data is in `y_noise`. The smoothed values generated from the Python script:

    ASAP.smooth(y_noise)

is different from the values shown from the demo site. You can tell because the smoothed values generated from the Python script produces a min-value of 0.010680608603816815 and a max-value of 0.48671462099352242. Whereas the demo site produces a plot that has a min-value near -1.0 and a max-value of +1.0.

**Comment by kexinrong** [comment] 2017-11-15 08:23
Thanks for the note! I am trying to reproduce the described problem. One question: which target resolution did you choose for the smoothing?

**Comment by seanlaw** [comment] 2017-11-15 10:41
Just the default of 1000

**Comment by seanlaw** [comment] 2017-11-15 14:34
I noticed that the `smooth` function in the Python script applies a transformation on the data immediately

    def smooth(data, resolution=1000):
        ildr        = int( len(data) / resolution )
        data        = SMA(data,ildr,ildr)  # Forced transformation here!!!

Whereas the Javascript (optimized) performs a check first:

    function smooth(data, resolution) {
        if (resolution < data.length) {
            data = SMA(data, Math.trunc(data.length / resolution),
                Math.trunc(data.length / resolution));
        } 

However, if I add the same check to the Python script then I encounter other problems executing the script.

**Comment by kexinrong** [comment] 2017-11-16 01:25
Yes, you are absolutely correct. The python script does not check for the case when the target resolution (1000) is larger than the number of data points (200) in your time series. I will push a fix for this to the master branch.

Can you elaborate on the "other problems" that you encountered?

**Comment by seanlaw** [comment] 2017-11-16 01:41
If you are able to get the above fake dataset working without Python throwing an error then we should be fine. I was using Pythong 2.7

**Comment by kexinrong** [comment] 2017-11-16 06:06
I pushed a fix to master and was able to get the script to successfully process the suggested input data. Thanks for your input!

**Closed by kexinrong** 2017-11-16 06:06 UTC

**Comment by seanlaw** [comment] 2017-11-16 20:56
@kexinrong I tried this code:

    n = 201
    x = np.linspace(0, 1, n)
    y = np.sin(4*np.pi*x*x)
    chirp = 0.5*np.sin((2.0*np.pi*x)/0.05)
    chirp_inx = np.argwhere((x > 0.4) & (x < 0.45))
    y[chirp_inx] = chirp[chirp_inx]
    noise = np.random.normal(0, 0.1, n)
    y_noise = y + noise
    y_smooth = ASAP.smooth(y_noise, resolution=1000)

And this is the error that I'm seeing:
<pre>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-7acc9650e543> in <module>()
      7 noise = np.random.normal(0, 0.1, n)
      8 y_noise = y + noise
----> 9 y_smooth = ASAP.smooth(y_noise, resolution=1000)

ASAP/python/ASAP.pyc in smooth(data, resolution)
     10     if ildr > 1:
     11         data    = SMA(data,ildr,ildr)
---> 12     acf         = ACF(data, round(len(data) / 10))
     13     peaks       = acf.peaks
     14     orig_kurt   = acf.kurtosis

ASAP/python/ASAP.pyc in __init__(self, values, max_lag)
    130     CORR_THRESH = 0.2
    131     def __init__(self, values, max_lag=None):
--> 132         super(ACF,self).__init__(values)
    133         if max_lag is None:
    134             max_lag = round(len(values)/10)

ASAP/python/ASAP.pyc in __init__(self, values)
     70 class Metrics(object):
     71     def __init__(self, values):
---> 72         self.set_values( values )
     73 
     74     def set_values(self,values):

ASAP/python/ASAP.pyc in set_values(self, values)
     73 
     74     def set_values(self,values):
---> 75         if not values:
     76             raise Exception("something is wrong, no values given")
     77         self.values = values

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
</pre>

**Comment by kexinrong** [comment] 2017-11-16 21:04
If you try 
> y_smooth = ASAP.smooth(list(y_noise), resolution=1000)
instead, it should run without error.

**Comment by seanlaw** [comment] 2017-11-16 23:24
Hmm, that seems really strange but, indeed, it works. May I recommend that If you're using numpy then you should probably consider using numpy arrays across the entire project for speed and consistency.

**Comment by kexinrong** [comment] 2017-11-16 23:35
Thanks for the suggestion. Right now the smoothing function assumes that the data is passed in as a plain list instead of a numpy array (since the data might have been extracted from a csv etc.). But in the future, converting everything to numpy array beforehand makes sense.
